Tensor Matriks

In [2]:
import numpy as np

In [3]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [5]:
#tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [7]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X.size


6

Matrices in PYTorch

In [15]:
import torch

In [16]:
import torch
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [17]:
X_pt.shape

torch.Size([3, 2])

In [18]:
X_pt[1,:]


tensor([ 5, 26])

Matrices in Tensorflow

In [19]:
import tensorflow as tf

In [20]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [22]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [23]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [24]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>