In [1]:
import numpy as np


In [2]:
#vector x dengan ukuran 3x1
x = np.array([18, 1, 8])


In [3]:
#hitung panjang vector x
len(x)

3

In [4]:
#tampilkan ukuran vector x
x.shape

(3,)

In [5]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
#akses elemen pertama dari vector x
x[0] # 0 adalah elemen pertama dalam array

np.int64(18)

In [7]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

Vector TRansposition

In [8]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([18,  1,  8])

In [9]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [10]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[18, 1, 8]])
y

array([[18,  1,  8]])

In [11]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

Vector in Pythorchand Tensorflow

In [12]:
import torch
import tensorflow as tf

In [13]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [14]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>